import SlActionSheet from '../components/sl-action-sheet/sl-action-sheet.vue';
import SlAddressBook from '../components/sl-address-book/sl-address-book.vue';
import SlBottom from '../components/sl-bottom/sl-bottom.vue';
import SlButton from '../components/sl-button/sl-button.vue';
import SlCard from '../components/sl-card/sl-card.vue';
import SlCheckbox from '../components/sl-checkbox/sl-checkbox.vue';
import SlCol from '../components/sl-col/sl-col.vue';
import SlDatePicker from '../components/sl-date-picker/sl-date-picker.vue';
import SlDropdown from '../components/sl-dropdown/sl-dropdown.vue';
import SlDropdownItem from '../components/sl-dropdown-item/sl-dropdown-item.vue';
import SlEmpty from '../components/sl-empty/sl-empty.vue';
import SlFillLine from '../components/sl-fill-line/sl-fill-line.vue';
import SlForm from '../components/sl-form/sl-form.vue';
import SlFormItem from '../components/sl-form-item/sl-form-item.vue';
import SlIcon from '../components/sl-icon/sl-icon.vue';
import SlIconText from '../components/sl-icon-text/sl-icon-text.vue';
import SlImage from '../components/sl-image/sl-image.vue';
import SlInput from '../components/sl-input/sl-input.vue';
import SlLine from '../components/sl-line/sl-line.vue';
import SlMask from '../components/sl-mask/sl-mask.vue';
import SlModal from '../components/sl-modal/sl-modal.vue';
import SlNavBar from '../components/sl-nav-bar/sl-nav-bar.vue';
import SlPage from '../components/sl-page/sl-page.vue';
import SlPicker from '../components/sl-picker/sl-picker.vue';
import SlPopup from '../components/sl-popup/sl-popup.vue';
import SlPopupHead from '../components/sl-popup-head/sl-popup-head.vue';
import SlRadio from '../components/sl-radio/sl-radio.vue';
import SlRow from '../components/sl-row/sl-row.vue';
import SlScrollRefresher from '../components/sl-scroll-refresher/sl-scroll-refresher.vue';
import SlSearch from '../components/sl-search/sl-search.vue';
import SlSelect from '../components/sl-select/sl-select.vue';
import SlSpaceGroup from '../components/sl-space-group/sl-space-group.vue';
import SlSpaceItem from '../components/sl-space-item/sl-space-item.vue';
import SlSwitch from '../components/sl-switch/sl-switch.vue';
import SlTable from '../components/sl-table/sl-table.vue';
import SlTabs from '../components/sl-tabs/sl-tabs.vue';
import SlTags from '../components/sl-tags/sl-tags.vue';
import SlTd from '../components/sl-td/sl-td.vue';
import SlTh from '../components/sl-th/sl-th.vue';
import SlTop from '../components/sl-top/sl-top.vue';
import SlTr from '../components/sl-tr/sl-tr.vue';
import '@vue/runtime-core';
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'sl-action-sheet': typeof SlActionSheet;
    'sl-address-book': typeof SlAddressBook;
    'sl-bottom': typeof SlBottom;
    'sl-button': typeof SlButton;
    'sl-card': typeof SlCard;
    'sl-checkbox': typeof SlCheckbox;
    'sl-col': typeof SlCol;
    'sl-date-picker': typeof SlDatePicker;
    'sl-dropdown': typeof SlDropdown;
    'sl-dropdown-item': typeof SlDropdownItem;
    'sl-empty': typeof SlEmpty;
    'sl-fill-line': typeof SlFillLine;
    'sl-form': typeof SlForm;
    'sl-form-item': typeof SlFormItem;
    'sl-icon': typeof SlIcon;
    'sl-icon-text': typeof SlIconText;
    'sl-image': typeof SlImage;
    'sl-input': typeof SlInput;
    'sl-line': typeof SlLine;
    'sl-mask': typeof SlMask;
    'sl-modal': typeof SlModal;
    'sl-nav-bar': typeof SlNavBar;
    'sl-page': typeof SlPage;
    'sl-picker': typeof SlPicker;
    'sl-popup': typeof SlPopup;
    'sl-popup-head': typeof SlPopupHead;
    'sl-radio': typeof SlRadio;
    'sl-row': typeof SlRow;
    'sl-scroll-refresher': typeof SlScrollRefresher;
    'sl-search': typeof SlSearch;
    'sl-select': typeof SlSelect;
    'sl-space-group': typeof SlSpaceGroup;
    'sl-space-item': typeof SlSpaceItem;
    'sl-switch': typeof SlSwitch;
    'sl-table': typeof SlTable;
    'sl-tabs': typeof SlTabs;
    'sl-tags': typeof SlTags;
    'sl-td': typeof SlTd;
    'sl-th': typeof SlTh;
    'sl-top': typeof SlTop;
    'sl-tr': typeof SlTr;
  }
}
